name: Update ICS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Generate ICS
        run: python generate_ics.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}

      - name: Commit calendar
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add calendar.ics

          git commit -m "update calendar" || echo "No changes"

          git push
